name:                accelerade
version:             0.1.0.0
github:              "githubuser/accelerade"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/accelerade#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate >= 1.2.0.1
- accelerate-llvm >= 1.0.0.0
- accelerate-llvm-native >= 1.0.0.0
- accelerate-llvm-ptx >= 1.0.0.0
- cuda >= 0.7.5.3
- llvm-hs >= 9
- llvm-hs-pure >= 9
- linear-accelerate >= 0.6.0.0
- linear
- numeric-limits >= 0.1.0.0
- vector

library:
  source-dirs: src

executables:
  accelerade-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerade

tests:
  accelerade-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerade
    - hspec
    - QuickCheck >= 2.13.2
    - timeit
